version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../:/workspace:cached
    command: sleep infinity
    environment:
      - GO111MODULE=on
      - CGO_ENABLED=0
    ports:
      - "8080:8080"
      - "2345:2345"
